sharpness =  [0,-1,0;
              -1,5,-1;
              0,-1,0];
horizontal_edge =  [-1,-1,-1;
                    0,0,0;
                    1,1,1];
embossing =[-2 , -1 , 0;
            -1 , 1 , 1 ;
            0 , 1 , 2];
gaussian = 1/273 *[1 , 4 , 7 , 4 , 1;
                  4 , 16 , 26 , 16 , 4;
                  7 , 26 , 41 , 26 , 7;
                  4 , 16 , 26 , 16 , 4;
                  1 , 4 , 7 , 4 , 1];
kitty_sharp = 'kitty_sharpness_valid_1.jpg';
ImageFolder = 'output_images/';
fullFileName = fullfile(ImageFolder,kitty_sharp);
kitty1 = conv2D('input_images/kitty.jpg' , 1 , false , sharpness);
imwrite(kitty1 , fullFileName);
kitty_horizontal = 'kitty_horizontaledge_same_2.jpg';
ImageFolder = 'output_images/';
fullFileName = fullfile(ImageFolder,kitty_horizontal);
kitty2 = conv2D('input_images/kitty.jpg' , 2 , true , horizontal_edge);
imwrite(kitty2 , fullFileName);
kitty_embossing = 'kitty_embossing_valid_3.jpg';
ImageFolder = 'output_images/';
fullFileName = fullfile(ImageFolder,kitty_embossing);
kitty3 = conv2D('input_images/kitty.jpg' , 3 , false , embossing);
imwrite(kitty3 , fullFileName);
kitty_gaussian = 'kitty_gaussian_same_1.jpg';
ImageFolder = 'output_images/';
fullFileName = fullfile(ImageFolder,kitty_gaussian);
kitty4 = conv2D('input_images/kitty.jpg' , 1 , true , gaussian);
imwrite(kitty4 , fullFileName);


lecun_sharp = 'lecun_sharpness_valid_1.jpg';
ImageFolder = 'output_images/';
fullFileName = fullfile(ImageFolder,lecun_sharp);
lecun1 = conv2D('input_images/lecun.jpg' , 1 , false , sharpness);
imwrite(lecun1 , fullFileName);
lecun_horizontal = 'lecun_horizontaledge_same_2.jpg';
ImageFolder = 'output_images/';
fullFileName = fullfile(ImageFolder,lecun_horizontal);
lecun2 = conv2D('input_images/lecun.jpg' , 2 , true , horizontal_edge);
imwrite(lecun2 , fullFileName);
lecun_embossing = 'lecun_embossing_valid_3.jpg';
ImageFolder = 'output_images/';
fullFileName = fullfile(ImageFolder,lecun_embossing);
lecun3 = conv2D('input_images/lecun.jpg' , 3 , false , embossing);
imwrite(lecun3 , fullFileName);
lecun_gaussian = 'lecun_gaussian_same_1.jpg';
ImageFolder = 'output_images/';
fullFileName = fullfile(ImageFolder,lecun_gaussian);
lecun4 = conv2D('input_images/lecun.jpg' , 1 , true , gaussian);
imwrite(lecun4 , fullFileName);


milad_sharp = 'milad_sharpness_valid_1.jpg';
ImageFolder = 'output_images/';
fullFileName = fullfile(ImageFolder,milad_sharp);
milad1 = conv2D('input_images/milad.jpg' , 1 , false , sharpness);
imwrite(milad1 , fullFileName);
milad_horizontal = 'milad_horizontaledge_same_2.jpg';
ImageFolder = 'output_images/';
fullFileName = fullfile(ImageFolder,milad_horizontal);
milad2 = conv2D('input_images/milad.jpg' , 2 , true , horizontal_edge);
imwrite(milad2 , fullFileName);
milad_embossing = 'milad_embossing_valid_3.jpg';
ImageFolder = 'output_images/';
fullFileName = fullfile(ImageFolder,milad_embossing);
milad3 = conv2D('input_images/milad.jpg' , 3 , false , embossing);
imwrite(milad3 , fullFileName);
milad_gaussian = 'milad_gaussian_same_1.jpg';
ImageFolder = 'output_images/';
fullFileName = fullfile(ImageFolder,milad_gaussian);
milad4 = conv2D('input_images/milad.jpg' , 1 , true , gaussian);
imwrite(milad4 , fullFileName);


mask_sharp = 'mask_sharpness_valid_1.jpg';
ImageFolder = 'output_images/';
fullFileName = fullfile(ImageFolder,mask_sharp);
mask1 = conv2D('input_images/mask.jpg' , 1 , false , sharpness);
imwrite(mask1 , fullFileName);
mask_horizontal = 'mask_horizontaledge_same_2.jpg';
ImageFolder = 'output_images/';
fullFileName = fullfile(ImageFolder,mask_horizontal);
mask2 = conv2D('input_images/mask.jpg' , 2 , true , horizontal_edge);
imwrite(mask2 , fullFileName);
mask_embossing = 'mask_embossing_valid_3.jpg';
ImageFolder = 'output_images/';
fullFileName = fullfile(ImageFolder,mask_embossing);
mask3 = conv2D('input_images/mask.jpg' , 3 , false , embossing);
imwrite(mask3 , fullFileName);
mask_gaussian = 'mask_gaussian_same_1.jpg';
ImageFolder = 'output_images/';
fullFileName = fullfile(ImageFolder,mask_gaussian);
mask4 = conv2D('input_images/mask.jpg' , 1 , true , gaussian);
imwrite(mask4 , fullFileName);